### ISSUE TITLE
Multibyte characters

### ISSUE THREAD

**Issue by ghost** [ThomasDickey/original-mawk#58] opened 2019-01-06 04:45 UTC
Gawk can handle multibyte characters:

~~~sh
$ gawk 'BEGIN { print "\302\266" }'
¶
~~~

However Mawk utterly fails:

~~~sh
$ mawk 'BEGIN { print "\302\266" }'
Â¶
~~~

**Comment by ThomasDickey** [comment] 2019-01-06 11:18
Duplicate of #43

**Closed as completed by ThomasDickey** 2019-01-06 11:18 UTC
